available_text_models: ["gpt-4-turbo", "gpt-4-32k", "gpt-4-vision", "gpt-3.5-turbo"]

info:
  gpt-4-turbo:
    type: chat_completion
    name: GPT-4 Turbo
    description: GPT-4 Turbo — это улучшенная версия GPT-4 с высокой скоростью и низкой стоимостью.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Smart: 5
      Fast: 5
      Cheap: 4

  gpt-4-32k:
    type: chat_completion
    name: GPT-4 32k
    description: GPT-4 с расширенным контекстом до 32k токенов. Отлично подходит для работы с большими документами.

    price_per_1000_input_tokens: 0.06
    price_per_1000_output_tokens: 0.12

    scores:
      Smart: 5
      Fast: 3
      Cheap: 2

  gpt-4-vision:
    type: chat_completion
    name: GPT-4 Vision
    description: Возможность понимать изображения и обрабатывать визуальные данные.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      Smart: 5
      Fast: 4
      Cheap: 3

  gpt-3.5-turbo:
    type: chat_completion
    name: GPT-3.5 Turbo
    description: GPT-3.5 Turbo — это быстрая и более доступная версия GPT-3.5, подходящая для повседневных задач.

    price_per_1000_input_tokens: 0.0015
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5
